<div>
<!--    <h1>Template.phtml</h1>-->
<!--    --><?php
//    echo $block->getLayout()->createBlock("NgocThanh\Module\Block\Block2")->setTemplate("NgocThanh_Module::template2.phtml")->toHtml();
//    echo $block->getLayout()->createBlock("NgocThanh\Module\Block\Block")->setTemplate("NgocThanh_Module::template3.phtml")->toHtml();

//    ?>
    <!--    --><?php
    //        echo $this->getChildHtml("module_block2");
    //    ?>
</div>



<?php
echo "<pre>";
var_dump($block->SiteMap());
echo "</pre>";
?>
