<?php

namespace NgocThanh\Module\Ui\Component;

class DataProvider extends \Magento\Ui\DataProvider\AbstractDataProvider
{
    public function __construct(
        $name,
        $primaryFieldName,
        $requestFieldName,
        \NgocThanh\Module\Model\ResourceModel\SiteMap\CollectionFactory $collectionFactory,
        array $meta = [],
        array $data = []
        )
    {

        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
        $this->collection = $collectionFactory->create();
//        var_dump($this->collection->getData());
    }

    public function getData()
    {
        return parent::getData(); // TODO: Change the autogenerated stub
    }

}

?>
